### ISSUE TITLE
Error: ERR: kbm-robot robot6.jar already started. appears if stopJar() and then run it again

### ISSUE THREAD

**Issue by Pashokus** [kylepaulsen/kbm-robot#2]

**Comment by kylepaulsen** [comment]
Thanks. Should be fixed now in v0.0.3 . Try updating kbm-robot.

**Comment by Pashokus** [comment]
Thanks. Error doesn't appear now. But I have another problem with repeatedly using. 
Steps: 
1. StartJar()
2. Execute some keyboard typing and stopJar().
3. StartJar() again and try to execute some keyboard typing.

Any errors are not appeared, but keyboard typing is not working.

**Comment by kylepaulsen** [comment]
Hmm not able to reproduce... I might need to see some code. Can you give me a sample?
Also do you need to stop the jar if you are going to be typing more stuff soon after?

**Comment by Pashokus** [comment]
Sorry. It was problems on my side. Thanks for quick fix.
