### ISSUE TITLE
event.data includes a newline

### ISSUE THREAD

**Issue by FlorianWendelborn** [kylepaulsen/kbm-robot#3]
(tested on Kubuntu 15)
Awesome module, but unfortunately every event includes a newline in the data field.

index.js

```
var gkm = require('gkm');

gkm.events.on('key.pressed', function (data) {
    console.log('\'' + data + '\'')
    console.log(this.event + ' ' + data);
});
```

output

```
'D
'
key.pressed D
```

Guess that's not intended, makes it much harder to work with at least.

**Comment by kylepaulsen** [comment]
Hmm... not really sure why gkm (didn't even know this module existed) is giving you a newline. Looking at my source, the jar that this module uses definitely doesn't press enter unless you tell it to. I can try and look into this soon.

**Comment by kylepaulsen** [comment]
So, I just tested your code sample. Only module used was gkm (just by itself). It appears to give a newline after the key pressed when I press a key on my keyboard. I don't think kbm-robot has anything to do with this issue. Maybe file an issue on [gkm's github page](https://github.com/tomzx/gkm)?

**Comment by FlorianWendelborn** [comment]
Oh my god, sorry. I was installing both of these modules at the same time and submitted the issue to the wrong repo. :unamused:

Will resubmit this to the correct repo then.
