### ISSUE TITLE
events.js:72  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Themis3000** [kylepaulsen/kbm-robot#5]
Ok, so considering that I am just 13 I have probably made some major mistake on my end... But I cannot find why this is not working...

Here's my code:
var robot = require('kbm-robot');

function right() {

robot.startJar();

robot.press("right")
     .sleep(100)
     .release("right")
     .go()
     .then(robot.stopJar);

}

function left() {

robot.startJar();

robot.press("left")
     .sleep(100)
     .release("left")
     .go()
     .then(robot.stopJar);

}

function up() {

robot.startJar();

robot.press("up")
     .sleep(100)
     .release("up")
     .go()
     .then(robot.stopJar);

}

function down() {

robot.startJar();

robot.press("down")
     .sleep(100)
     .release("down")
     .go()
     .then(robot.stopJar);

}

up();

when ever I try and execute my code I run in to this error: 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at Pipe.onread (net.js:558:19)

But here's the weird part... yesterday it worked 1/8 of the time that I executed it, and I have not changed a thing... I recorded the video from yesterday:
[Screencast_08-14-2016_09:38:33 PM.webm.zip](https://github.com/kylepaulsen/kbm-robot/files/418442/Screencast_08-14-2016_09.38.33.PM.webm.zip)

**Comment by kylepaulsen** [comment]
Try removing all start and stop jar calls and then adding one start jar
call under the require.

**Comment by Themis3000** [comment]
Thank you SO much!!! It works perfect now!!!
